# Run: docker build -t local_jenkins .

FROM jenkins/jenkins:lts
LABEL maintainer="user@gmail.com"

USER root
#RUN apt-get -y update && apt-get -y upgrade

#RUN mkdir /var/log/jenkins   &&  chown -R jenkins:jenkins /var/log/jenkins
#RUN mkdir /var/cache/jenkins &&  chown -R jenkins:jenkins /var/cache/jenkins

# For main web interface
EXPOSE 8443

# For attached agents
EXPOSE 50000

USER jenkins

#ENV JAVA_OPTS="-Xmx8192m"
#ENV JENKINS_OPTS="--handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war"
